/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {Button, ScrollView, StyleSheet, Text, View} from 'react-native';
import {discoverScales, registerStarListener, setupScales, connectScale} from 'react-native-star-micronics-io';

export default class App extends Component {
  state = {scale: null, data: null};

  componentDidMount() {
    setupScales();

    registerStarListener("onDiscoverScale", (scale) => {
      this.setState({scale});
    });

    registerStarListener("onScaleConnect", () => {
      this.setState({data: {weight: "0", unit: "dogs"}});
    });

    registerStarListener("onScaleDisconnect", () => {
      alert("Scale has disconnected");

      this.setState({data: null, scale: null});
    });

    registerStarListener("onScaleData", (data) => {
      this.setState({data});
    });
  }

  renderConnectButton() {
    const {scale, data} = this.state;

    if (scale === null) {
      return (
        <Button title="Discover Scale" onPress={() => discoverScales()} />
      )
    }

    if (data === null) {
      return (
        <Button title="Connect to Scale" onPress={() => connectScale(scale)} />
      );
    }
  }

  render() {
    const {scale, data} = this.state;

    return (
      <ScrollView style={{flex: 1}}>
        {this.renderConnectButton()}

        {scale && (
          <View>
            <Text>{scale.id}</Text>
            <Text>{scale.name}</Text>
            <Text>{scale.type}</Text>
            <Text>{scale.description}</Text>
          </View>
        )}

        {data && (
          <View>
            <Text>{data.weight}{data.unit}</Text>
          </View>
        )}
      </ScrollView>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
